apiVersion: v1
kind: Service
metadata:
  name: {{ include "tiger.fullname" . }}-api
  labels:
    {{- include "tiger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      protocol: TCP
      name: api
  selector:
    {{- include "tiger.selectorLabels" . | nindent 4 }}
