apiVersion: v1
kind: ConfigMap
metadata:
  name: tg-config
  labels:
    app: tigergraph
    {{- include "tiger.labels" . | nindent 4 }}
data:
  init_tg_cfg: |
    System.HostList=[
    {{ $count := (.Values.replicaCount | add1 | int ) }}
    {{- range $k, $v := untilStep 1 $count 1 }}
    {"ID":"m{{ $v }}":, "Hostname": "tigergraph-{{ $k }}", "Region":""}{{ if ne ($v | add1) $count }},{{end}}
    {{- end }}
    ]
    System.SSH.User.Username=tigergraph
    System.SSH.User.Password=tigergraph
    System.SSH.User.Privatekey=/home/tigergraph/.ssh/tigergraph_rsa
    System.DataRoot=/home/tigergraph/tigergraph/data
    System.LogRoot=/home/tigergraph/tigergraph/log
    System.TempRoot=/tmp
