# Note: change storage class as appropriate
# TODO: Add storage class to values.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-ingest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
