apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "tiger.selectorLabels" . | nindent 4 }}
  name: tg-external-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: tigergraph
  ports:
  - port: 9000
    name: rest
    targetPort: 9000
  - port: 14240
    name: graphstudio
    targetPort: 14240
