apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-ui
  labels:
    app: tigergraph
    {{- include "tiger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.uiService.type }}
  ports:
    - port: {{ .Values.uiService.port }}
      targetPort: {{ .Values.uiService.targetPort }}
      nodePort: {{ .Values.uiService.nodePort }}
      protocol: TCP
      name: ui
  selector:
    {{- include "tiger.selectorLabels" . | nindent 4 }}
