;; the whole dang thing
(specifications->manifest
 '(
   "file"
   "docker-cli"
   "curl"
   "libvirt"
   "acpi"
   "aspell"
   "brightnessctl"
   "cowsay"
   "curl"
   ;; "emacs-desktop-environment"
   ;; "emacs-emacsql-sqlite3"
   ;; "emacs-sqlite"
   ;; "emacs-vterm"
   "espeak"
   "font-google-material-design-icons"
   "fortune-mod"
   "gnupg"
   "hicolor-icon-theme"
   "htop"
   "jq"
   "libnotify"
   "lm-sensors"
   "papirus-icon-theme"
   ;; "rbw"  ;; bitwarden cli
   ;; "slim" ;; alternative DM
   "speedtest-cli"
   "tree"
   ;; "ungoogled-chromium"
   "upower"
   "vim-guix-vim"
   "xdotool"
   "xev"
   "xmodmap"
   "xterm"
   "xwininfo"
   ))
