apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: default
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: gregoryg/sh-net-utils
    name: task-pv-pod
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-p24xz
      readOnly: true
    - mountPath: /gort
      name: task-pv-pod
  volumes:
  - name: default-token-p24xz
    secret:
      defaultMode: 420
      secretName: default-token-p24xz
  - name: task-pv-pod
    persistentVolumeClaim:
      claimName: iscsipvc
